
    create table BandejaDeMensajes (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table BandejaDeMensajes_mensajes (
        BandejaDeMensajes_id bigint not null,
        descripcion varchar(255),
        fechaYHora varbinary(255),
        leido boolean not null
    )

    create table Entidad (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Item (
        id bigint generated by default as identity (start with 1),
        cantidad integer not null,
        producto_id bigint,
        operacion_id bigint,
        primary key (id)
    )

    create table MediosDePago (
        tipo_pago varchar(1) not null,
        id bigint generated by default as identity (start with 1),
        codigoPago varchar(255),
        fechaVencimiento varbinary(255),
        nombreCompleto varchar(255),
        numTarjeta varchar(255),
        primary key (id)
    )

    create table OperacionDeEgreso (
        id bigint generated by default as identity (start with 1),
        cantidadPresupuestosRequeridos integer not null,
        f_Operacion timestamp,
        informada boolean,
        pathArchivo varchar(255),
        valorTotal double,
        entidad_id bigint,
        pago_id bigint,
        proveedor_id bigint,
        usuarioAlta_id bigint,
        primary key (id)
    )

    create table PasswordHashedAndSalted (
        id bigint generated by default as identity (start with 1),
        hash varbinary(255),
        salt varbinary(255),
        primary key (id)
    )

    create table Producto (
        id bigint generated by default as identity (start with 1),
        idProducto varchar(255),
        nombre varchar(255),
        precioUnitario double,
        primary key (id)
    )

    create table Proveedor (
        id bigint generated by default as identity (start with 1),
        codigoID integer not null,
        razonSocial varchar(255),
        tipoDeCodigoID integer,
        primary key (id)
    )

    create table Usuario (
        id bigint generated by default as identity (start with 1),
        idUsuario varchar(255),
        tipo_usuario varchar(255),
        bandeja_id bigint,
        passwordHashedAndSalted_id bigint,
        primary key (id)
    )

    alter table BandejaDeMensajes_mensajes 
        add constraint FK_raer0a32bi1iikyuc6hr60voa 
        foreign key (BandejaDeMensajes_id) 
        references BandejaDeMensajes

    alter table Item 
        add constraint FK_f7hy962nag2m6b15woe3qhq7y 
        foreign key (producto_id) 
        references Producto

    alter table Item 
        add constraint FK_ctk8llh5yxfw6epj6uigjhaof 
        foreign key (operacion_id) 
        references OperacionDeEgreso

    alter table OperacionDeEgreso 
        add constraint FK_cub84362wthi77sojrjeo98o7 
        foreign key (entidad_id) 
        references Entidad

    alter table OperacionDeEgreso 
        add constraint FK_6f7ttpws4ifeqqdbc19p9ce96 
        foreign key (pago_id) 
        references MediosDePago

    alter table OperacionDeEgreso 
        add constraint FK_14k7g14y9ln23d1vdaffiq2wq 
        foreign key (proveedor_id) 
        references Proveedor

    alter table OperacionDeEgreso 
        add constraint FK_ovrpd6tv7sx38118t2dwdaoyq 
        foreign key (usuarioAlta_id) 
        references Usuario

    alter table Usuario 
        add constraint FK_ip6vgtgugxe3o6gjaw8gnt4om 
        foreign key (bandeja_id) 
        references BandejaDeMensajes

    alter table Usuario 
        add constraint FK_5vkunjox39h8yfq5deaej1v20 
        foreign key (passwordHashedAndSalted_id) 
        references PasswordHashedAndSalted
